SELECT DISTINCT C.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
WHERE 
    C.CAR_TYPE = '세단' AND
    H.START_DATE LIKE '2022-10%'
ORDER BY C.CAR_ID DESC