SELECT B.CATEGORY, B.PRICE AS MAX_PRICE, B.PRODUCT_NAME
FROM (
    SELECT CATEGORY, MAX(PRICE) AS PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
    HAVING CATEGORY IN ('과자', '국', '김치', '식용유')
) A
LEFT JOIN FOOD_PRODUCT B
ON A.CATEGORY = B.CATEGORY AND A.PRICE = B.PRICE
ORDER BY MAX_PRICE DESC