SELECT 
    CASE WHEN PRICE < 10000 THEN 0
    ELSE TRUNCATE(PRICE, -4) # 4자리 버리기 (양수면 소수점, 음수면 0의 수,,,)
    END AS PRICE_GROUP,
    COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP